services:
  app:
    image: stonesea/ilock-http-service:2.3.0
    container_name: ilock_http_service
    restart: always
    ports:
      - '20033:20033'
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - ENV_TYPE=SERVER
      - ALIYUN_ACCESS_KEY=${ALIYUN_ACCESS_KEY}
      - ALIYUN_RTC_APP_ID=${ALIYUN_RTC_APP_ID}
      - ALIYUN_RTC_REGION=${ALIYUN_RTC_REGION}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - LOCAL_DB_HOST=db
      - LOCAL_DB_USER=root
      - LOCAL_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - LOCAL_DB_NAME=${MYSQL_DATABASE}
      - LOCAL_DB_PORT=3306
      - SERVER_DB_HOST=db
      - SERVER_DB_USER=root
      - SERVER_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SERVER_DB_NAME=${MYSQL_DATABASE}
      - SERVER_DB_PORT=3306
      - MQTT_BROKER_URL=tcp://mqtt:1883
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    networks:
      - ilock_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:20033/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    container_name: ilock_mysql
    restart: always
    ports:
      - '3310:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=1000
      - --innodb_buffer_pool_size=1G
    networks:
      - ilock_network
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.0-alpine
    container_name: ilock_redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - ilock_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: ilock_mqtt
    restart: always
    ports:
      - '1884:1883'
      - '8883:8883'
      - '9001:9001'
    volumes:
      - ./internal/infrastructure/mqtt/config:/mosquitto/config
      - ./internal/infrastructure/mqtt/data:/mosquitto/data
      - ./internal/infrastructure/mqtt/log:/mosquitto/log
      - ./internal/infrastructure/mqtt/certs:/mosquitto/certs
    networks:
      - ilock_network
    healthcheck:
      test:
        [
          'CMD',
          '/usr/bin/mosquitto_sub',
          '-t',
          '$$SYS/#',
          '-C',
          '1',
          '-i',
          'healthcheck',
          '-W',
          '3',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  ilock_network:
    driver: bridge

volumes:
  mysql_data:
    name: ilock_mysql_data
  redis_data:
    name: ilock_redis_data
