services:
  app:
    image: stonesea/ilock-http-service:1.3.0
    container_name: ilock_http_service
    restart: always
    ports:
      - '20033:20033'
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - ENV_TYPE=SERVER
      - ALIYUN_ACCESS_KEY=${ALIYUN_ACCESS_KEY}
      - ALIYUN_RTC_APP_ID=${ALIYUN_RTC_APP_ID}
      - ALIYUN_RTC_REGION=${ALIYUN_RTC_REGION}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ilock_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:20033/api/ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0
    container_name: ilock_mysql
    restart: always
    ports:
      - '3310:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ilock_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0-alpine
    container_name: ilock_redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - ilock_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: ilock_mqtt
    restart: always
    ports:
      - '1883:1883'
      - '8883:8883'
      - '9001:9001'
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - ilock_network
    healthcheck:
      test: ['CMD', 'mosquitto_sub', '-t', '$$SYS/#', '-C', '1', '-i', 'healthcheck', '-W', '3']
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ilock_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
